export type TNoteType = 1|2|3|4|5|6|7|8|9|10|11|12;
/* eslint-disable camelcase */
export interface INote {
  id: string,
  diary_id: number,
  server_created_at: number,
  server_updated_at: number,
  server_deleted_at: number,
  created_at: number,
  updated_at: number,
  note_type:  TNoteType,
  date_event_start: number | null,
  date_event_end: number | null,
  photo: string | null,
  food: string | null,
  volume: string | null,
  note: string | null,
  duration: string | null,
  milk_volume_left: string | null,
  milk_volume_right: string | null,
  type: string | null,
  achievement: string | null,
  weight: string | null,
  growth: string | null,
  head_circle: string | null,
  temp: number | null,
  tags: string | null,
  pressure: string | null,
}