require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'RNTempl' do
  config = use_native_modules!

  pod 'GoogleSignIn', '~> 5.0.2'

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )
  pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi', :modular_headers => true
# NOTE: This is required as of v0.23
  pod 'simdjson', path: '../node_modules/@nozbe/simdjson'

  target 'RNTemplTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
    use_flipper!({ 'Flipper-Folly' => '2.5.3', 'Flipper' => '0.87.0', 'Flipper-RSocket' => '1.3.1' })
    ENVFILES = {
      'Debug' => '$(PODS_ROOT)/../../.env.development',
      'Staging' => '$(PODS_ROOT)/../../.env.staging',
      'Release' => '$(PODS_ROOT)/../../.env.production',
    }

    post_install do |installer|
      flipper_post_install(installer)
      react_native_post_install(installer)
      installer.pods_project.targets.each do |target|
            target.build_configurations.each do |config|
              if target.name == 'react-native-config'
                config.build_settings['ENVFILE'] = ENVFILES[config.name]
              end
            end
      end
    end
end