import {ImageURISource} from 'react-native';

export const Images = {
  add: <ImageURISource>require('../../assets/images/add.png'),
  bell: <ImageURISource>require('../../assets/images/bell.png'),
  diary: <ImageURISource>require('../../assets/images/diary.png'),
  page: <ImageURISource>require('../../assets/images/newspapaper.png'),
  arrowDown: <ImageURISource>require('../../assets/images/arrowDown.png'),
  arrowBack: <ImageURISource>require('../../assets/images/arrowBack.png'),
  arrowBackFull: <ImageURISource>require('../../assets/images/outline_arrow_back.png'),
  photo: <ImageURISource>require('../../assets/images/photo.png'),
  delete: <ImageURISource>require('../../assets/images/delete.png'),
  bookmarkFilled: <ImageURISource>require('../../assets/images/outline_bookmark_black.png'),
  bookmarkBorder: <ImageURISource>require('../../assets/images/outline_bookmark_border_black.png'),
  edit: <ImageURISource>require('../../assets/images/outline_edit_black.png'),
  done: <ImageURISource>require('../../assets/images/outline_check_circle.png'),
  cancel: <ImageURISource>require('../../assets/images/outline_cancel.png'),
  gallery: <ImageURISource>require('../../assets/images/outline_gallery.png'),
  camera: <ImageURISource>require('../../assets/images/outline_photo_camera.png'),
  cameraSmile: <ImageURISource>require('../../assets/images/camera_with_face.png'),
  addPhotoAlternate: <ImageURISource>require('../../assets/images/add_photo_alternate.png'),
  playlistAdd: <ImageURISource>require('../../assets/images/playlist_add.png'),
  user: <ImageURISource>require('../../assets/images/user.png'),
  adBlock: <ImageURISource>require('../../assets/images/adBlock.png'),
  clipboard: <ImageURISource>require('../../assets/images/clipboard.png'),
  cloudSync: <ImageURISource>require('../../assets/images/csync.png'),
  writing: <ImageURISource>require('../../assets/images/writing.png'),
  export: <ImageURISource>require('../../assets/images/export.png'),
  import: <ImageURISource>require('../../assets/images/import.png'),
  languages: <ImageURISource>require('../../assets/images/languages.png'),
  insurance: <ImageURISource>require('../../assets/images/insurance.png'),
  rate: <ImageURISource>require('../../assets/images/rate.png'),
  contract: <ImageURISource>require('../../assets/images/contract.png'),
  check: <ImageURISource>require('../../assets/images/check.png'),
  language: <ImageURISource>require('../../assets/images/language.png'),
};
